### ISSUE TITLE
demo无法正常跳转到插件

### ISSUE THREAD

**Issue by youyuanme** [doujd/PluginDemo1#1]
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:670)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at com.plugin_app.BaseActivity.setContentView(BaseActivity.java:42)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at com.plugin_app.MainActivity.onCreate(MainActivity.java:13)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at com.plugindemo1.ProxyActivity.onCreate(ProxyActivity.java:36)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.Activity.performCreate(Activity.java:6367)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:165)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.os.Looper.loop(Looper.java:150)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5546)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
01-08 15:24:40.735 23086-23086/top.vimerzhao.hookplugindemo D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
01-08 15:24:40.736 23086-23086/top.vimerzhao.hookplugindemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.vimerzhao.hookplugindemo, PID: 23086
    java.lang.RuntimeException: Unable to start activity ComponentInfo{top.vimerzhao.hookplugindemo/com.plugindemo1.ProxyActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
        at android.app.ActivityThread.access$900(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
     Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:670)
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at android.support.v7.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:299)
        at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:98)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1191)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
        at android.app.ActivityThread.access$900(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5546) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
01-08 15:24:40.751 23086-23086/top.vimerzhao.hookplugindemo I/Process: Sending signal. PID: 23086 SIG: 9

**Comment by doujd** [comment]
不好意思  刚看到
 我加你qq了 。

你确认下那个插件的apk 是否在sd卡  还有sd卡的权限是否启用 demo里面未处理






At 2020-01-08 15:27:43, "youyuanme" <notifications@github.com> wrote:

01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:670)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at com.plugin_app.BaseActivity.setContentView(BaseActivity.java:42)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at com.plugin_app.MainActivity.onCreate(MainActivity.java:13)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at com.plugindemo1.ProxyActivity.onCreate(ProxyActivity.java:36)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.Activity.performCreate(Activity.java:6367)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.ActivityThread.access$900(ActivityThread.java:165)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.os.Looper.loop(Looper.java:150)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at android.app.ActivityThread.main(ActivityThread.java:5546)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at java.lang.reflect.Method.invoke(Native Method)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
01-08 15:24:40.732 23086-23086/top.vimerzhao.hookplugindemo W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
01-08 15:24:40.735 23086-23086/top.vimerzhao.hookplugindemo D/AndroidRuntime: Shutting down VM

--------- beginning of crash



01-08 15:24:40.736 23086-23086/top.vimerzhao.hookplugindemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: top.vimerzhao.hookplugindemo, PID: 23086
java.lang.RuntimeException: Unable to start activity ComponentInfo{top.vimerzhao.hookplugindemo/com.plugindemo1.ProxyActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
at android.app.ActivityThread.access$900(ActivityThread.java:165)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5546)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:670)
at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
at android.support.v7.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:299)
at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:98)
at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1191)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
at android.app.ActivityThread.access$900(ActivityThread.java:165) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:150) 
at android.app.ActivityThread.main(ActivityThread.java:5546) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
01-08 15:24:40.751 23086-23086/top.vimerzhao.hookplugindemo I/Process: Sending signal. PID: 23086 SIG: 9

**Comment by youyuanme** [comment]
问题解决了，非常感谢你的回答
